### ISSUE TITLE
Default export not a function?

### ISSUE THREAD

**Issue by cwervo** [11ty/eleventy-plugin-syntaxhighlight#16]
Hi!

I'm not sure exactly what's going on but when I use:

```js
const syntaxHighlight = require("@11ty/eleventy-plugin-syntaxhighlight");

module.exports = function(eleventyConfig) {
    // ... config stuff
    eleventyConfig.addPlugin(syntaxHighlight);
```

I get:

```sh
$ eleventy --serve --watch
/usr/local/lib/node_modules/@11ty/eleventy/src/UserConfig.js:255
      throw new Error(
      ^

Error: EleventyConfig.addPlugin expects the first argument to be a function.
    at UserConfig.addPlugin (/usr/local/lib/node_modules/@11ty/eleventy/src/UserConfig.js:255:13)
    at module.exports (/Users/andrescuervo/code/cwervo.com/.eleventy.js:10:20)
    at TemplateConfig.mergeConfig (/usr/local/lib/node_modules/@11ty/eleventy/src/TemplateConfig.js:92:21)
    at new TemplateConfig (/usr/local/lib/node_modules/@11ty/eleventy/src/TemplateConfig.js:20:24)
    at Object.<anonymous> (/usr/local/lib/node_modules/@11ty/eleventy/src/Config.js:5:14)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

However, if I use:

```
eleventyConfig.addPlugin(syntaxHighlight.configFunction);
```

Everything works as expected. ¯\_(ツ)_/¯

**Comment by zachleat** [comment]
Eleventy hasn’t had that specific error message language since v0.5.3: https://github.com/11ty/eleventy/blob/v0.5.3/src/UserConfig.js#L229

It switched to work with `configFunction` signatures in 0.5.4. Please upgrade your Eleventy version!

**Comment by zachleat** [comment]
I’ll update the `peerDependency` for this to also reflect 0.5.4+

**Comment by zachleat** [comment]
> This is an automated message to let you know that a helpful response was posted to your issue and for the health of the repository issue tracker the issue will be closed. This is to help alleviate issues hanging open waiting for a response from the original poster.

> If the response works to solve your problem—great! But if you’re still having problems, do not let the issue’s closing deter you if you have additional questions! Post another comment and I will reopen the issue. Thanks!
